- name: configure frontend server
  become: yes
  hosts: frontend
  tasks:
  - name: install nginx server 
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove default content from web server
    ansible.builtin.file:
      path: /usr/share/nginx/html  #delete html directory as * is not deleting anything
      state: absent

  - name: create html directory
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: directory


 # ansible unarchive module has a code taht can unarchive a file that needs to be downloaded
  - name: download and Unzip frontend code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy Nginx Reverse Proxy Configuration
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
     name: nginx
     state: restarted

  

  